pipeline {
  agent any
   agent { label 'AGENT-01' }
  stages {
    stage('Build') {
      steps {
        echo 'This is Build.'
      }
    }
    stage('Test') {
      steps {
        echo 'This is Running Test.'
      }
    }
    stage('Deploy') {
      steps {
        echo 'This is Deploying.'
      }
    }
  }
}
