pipeline {
   agent { label 'AGENT-01' }
  stages {
    stage('Build') {
      steps {
        echo 'This is Build.'
      }
    }
    stage('Test') {
      steps {
        echo 'This is Running Test.'
      }
    }
    stage('Deploy') {
      steps {
        echo 'This is Deploying.'
      }
    }
  }
   post { 
        always { 
            echo 'I will always say Hello again!'
        }
        failure { 
            echo 'I will run when pipline failure!'
        }
        success { 
            echo 'I will run when pipline success!'
        }
    }
}
