pipeline {
    agent { label 'AGENT-01' }

    stages {
        stage('Clone Repository') {
            steps {
                git 'https://github.com/krishnatummeti/Jenkins.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'pip install -r requirements.txt'
            }
        }

        stage('Run Tests') {
            steps {
                script {
                    sh """
                        python3 test_app.py
                    """
                }
            }
        }

        stage('Deploy') {
            steps {
                script {
                    sh """
                        echo 'Deploying Application...'
                        echo 'Deployment step complete.'
                    """
                }
            }
        }
    }
}
