pipeline {
    agent { label 'AGENT-01' }

    stages {
        stage('Clone Repository') {
            steps {
                git 'https://github.com/krishnatummeti/Jenkins.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh '''
                    cd 05_flask-ci-cd-pipeline
                    pip install -r requirements.txt
                '''
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                    cd 05_flask-ci-cd-pipeline
                    python3 test_app.py
                '''
            }
        }

        stage('Deploy') {
            steps {
                sh '''
                    cd 05_flask-ci-cd-pipeline
                    echo "Deploying Application..."
                    echo "Deployment step complete."
                '''
            }
        }
    }
}
