pipeline {
    agent { label 'AGENT-01' }
    environment {
        client  = 'TECH Base Hub'
        project = 'Health checks for DB and Apps'
        server  = 'Test'
        authore = 'Mr Krishna'
    }
    options { 
        disableConcurrentBuilds() 
    }
    stages {
        stage('Build') {
            steps {
                script {
                    sh """
                        echo 'This is Build.'
                        echo 'Client : ${env.client}'
                    """
                }
            }
        }
        stage('Test') {
            steps {
                script {
                    sh """
                        echo 'This is Running Test.'
                        echo 'Project: ${env.project}'
                    """
                }
            }
        }

        stage('Deploy') {
            input {
                message "Should we continue?"
                ok "Yes, we should."
                submitter "devuser"
                parameters {
                    string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')
                }
            }
            steps {
                script {
                    def person = params.PERSON
                    sh """
                        echo 'This is Deploying.'
                        echo 'Hello, ${person}'
                        echo 'Server: ${env.server}'
                        sleep 15
                        echo 'Test the server post validations'
                    """
                }
            }
        }
    }

    post {
        success {
            echo 'I will run when pipeline success!'
        }
        failure {
            echo 'I will run when pipeline failure!'
        }
    }
}
