pipeline {
    agent { label 'AGENT-01' }
    environment {
        client = 'TECH Base Hub'
        project = 'Health checks for DB and Apps'
        server    = 'Test'
    }
    options { 
        disableConcurrentBuilds() 
    }
    stages {
        stage('Build') {
            steps {
                script {
                  sh """
                    echo 'This is Build.'
                    echo 'Client : $client '
                """
                }
            }
        }
        stage('Test') {
            steps {
                script {
                  sh """
                    echo 'This is Running Test.'
                    echo 'Project: $client'
                    sleep 15
                """
                }
            }
        }
        stage('Deploy') {
            input {
                message "Should we continue?"
                ok "Yes, we should."
                submitter "alice,bob"
                parameters {
                    string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')
                }
            }
            steps {
                script {

                  sh """
                    echo 'This is Deploying.'
                    echo 'ServerL: $server'
                    echo 'test the server post validations'
                """
                }
            }
        }
    }
    post {
        success {
            echo 'I will run when pipeline success!'
        }
        failure {
            echo 'I will run when pipeline failure!'
        }
    }
}
