pipeline {
    agent { label 'AGENT-01' }
    parameters {
        string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')

        text(name: 'BIOGRAPHY', defaultValue: '', description: 'Enter some information about the person')

        booleanParam(name: 'TOGGLE', defaultValue: true, description: 'Toggle this value')

        choice(name: 'CHOICE', choices: ['One', 'Two', 'Three'], description: 'Pick something')

        password(name: 'PASSWORD', defaultValue: 'SECRET', description: 'Enter a password')
    }
    environment {
        client = 'TECH Base Hub'
        project = 'Health checks for DB and Apps'
        server    = 'Test'
    }
    options { 
        disableConcurrentBuilds() 
    }
    stages {
        stage('Build') {
            steps {
                script {
                  sh """
                    echo 'This is Build.'
                    echo 'Client : $client '
                    echo "Hello ${params.PERSON}"

                    echo "Biography: ${params.BIOGRAPHY}"

                    echo "Toggle: ${params.TOGGLE}"

                    echo "Choice: ${params.CHOICE}"

                    echo "Password: ${params.PASSWORD}"
                """
                }
            }
        }
        stage('Test') {
            steps {
                script {
                  sh """
                    echo 'This is Running Test.'
                    echo 'Project: $client'
                    sleep 15
                """
                }
            }
        }

        stage('Deploy') {
            steps {
                script {

                  sh """
                    echo 'This is Deploying.'
                    echo 'ServerL: $server'
                """
                }
            }
        }
    }

    post {
        success {
            echo 'I will run when pipeline success!'
        }
        failure {
            echo 'I will run when pipeline failure!'
        }
    }
}
