pipeline {
    agent { label 'AGENT-01' }

    options {
        skipStagesAfterUnstable()
    }

    stages {
        stage('Build') {
            steps {
                dir('06_simple-java-maven-app') {
                    sh 'mvn -B -DskipTests clean package'
                }
            }
        }
        stage('Test') {
            steps {
                dir('06_simple-java-maven-app') {
                    sh 'mvn test'
                }
            }
            post {
                always {
                    dir('06_simple-java-maven-app') {
                        junit 'target/surefire-reports/*.xml'
                    }
                }
            }
        }
        stage('Deliver') {
            steps {
                dir('06_simple-java-maven-app') {
                    sh './jenkins/scripts/deliver.sh'
                }
            }
        }
    }
}
