/* Requires the Docker Pipeline plugin */
pipeline {
    agent any
    stages {
        stage('build') {
            steps {
                sh """
                    echo "This is build"
                """
            }
        stage('test') {
            steps {
                sh """
                    echo "This is test"
                """
            }
        stage('build') {
            steps {
                sh """
                    echo "This is build"
                """
            }
        }
    }
}