pipeline {
    agent { label 'AGENT-01' }

    stages {
        stage('Install Dependencies') {
            steps {
                dir('05_node-js--app') {
                    sh 'npm install'
                }
            }
        }

        stage('Test') {
            steps {
                dir('05_node-js--app') {
                    sh 'npm test'
                }
            }
        }

        stage('Run App') {
            steps {
                dir('05_node-js--app') {
                    sh 'nohup node index.js > app.log 2>&1 &'
                    echo '✅ App started'
                }
            }
        }
    }

    post {
        success {
            echo '🎉 Build completed successfully!'
        }
        failure {
            echo '❌ Build failed.'
        }
    }
}
