pipeline {
    agent { label 'flask-builder-node' }

    environment {
        IMAGE_NAME = "flask-ci-cd-demo"
        CONTAINER_NAME = "flask-app"
        PROJECT_DIR = "05_flask-jenkins-project"
    }

    stages {

        stage('Clone Code') {
            steps {
                echo 'Code already cloned by Jenkins.'
                sh 'ls -l'
            }
        }

        stage('Install Dependencies') {
            steps {
                echo 'Installing Python dependencies...'
                sh 'python3 -m pip install -r $PROJECT_DIR/requirements.txt'
            }
        }

        stage('Run Unit Tests') {
            steps {
                echo 'Running unit tests...'
                sh 'python3 -m unittest discover $PROJECT_DIR/tests'
            }
        }

        stage('Build Docker Image') {
            steps {
                echo 'Building Docker image...'
                sh "docker build -t $IMAGE_NAME $PROJECT_DIR"
            }
        }

        stage('Run App in Container') {
            steps {
                echo 'Running Docker container...'
                sh """
                    docker rm -f $CONTAINER_NAME || true
                    docker run -d --name $CONTAINER_NAME -p 5000:5000 $IMAGE_NAME
                """
            }
        }
    }

    post {
        always {
            echo '✅ Pipeline finished.'
        }
    }
}
