pipeline {
    agent { label 'flask-builder-node' }

    environment {
        IMAGE_NAME = "flask-ci-cd-demo"
        CONTAINER_NAME = "flask-app"
    }

    stages {
        stage('Clone Code') {
            steps {
                echo 'Code already cloned by Jenkins.'
                sh 'ls -l'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'pip install -r requirements.txt'
            }
        }

        stage('Run Unit Tests') {
            steps {
                sh 'python3 -m unittest discover tests'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh "docker build -t $IMAGE_NAME ."
            }
        }

        stage('Run App in Container') {
            steps {
                sh """
                docker rm -f $CONTAINER_NAME || true
                docker run -d --name $CONTAINER_NAME -p 5000:5000 $IMAGE_NAME
                """
            }
        }
    }

    post {
        always {
            echo '✅ Pipeline finished.'
        }
    }
}
