pipeline {
    agent { label 'AGENT-01' }

    options {
        skipStagesAfterUnstable()
    }

    stages {
        stage('Build') {
            steps {
                dir('06_springboot-maven-demo') {
                    sh 'mvn -B clean package -DskipTests'
                }
            }
        }

        stage('Test') {
            steps {
                dir('06_springboot-maven-demo') {
                    sh 'mvn test'
                }
                // This is the correct place to archive reports
                junit '06_springboot-maven-demo/target/surefire-reports/*.xml'
            }
        }

        stage('Deliver') {
            steps {
                dir('06_springboot-maven-demo') {
                    sh './jenkins/scripts/deliver.sh'
                }
            }
        }
    }
}
